server:
  port: 8080

spring:
  devtools:
    livereload:
      port: 35729
  liquibase:
    change-log: classpath:changelog.yml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecofin
    username: ecofin
    password: ecofin
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id: ECOFIN_GROUP_EVENT
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all

request-validation:
  consumers:
    - service-name: "ecofin-front"
      always-allowed: true

topics:
  confirmation-topic: "ECOFIN_CONFIRMATION_PHONE_TOPIC"
  send-code-topic: "ECOFIN_SEND_CODE_TOPIC"

logging:
  level:
    org:
      apache:
        kafka: OFF
    kafka: OFF