server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
    consumer:
      group-id: ECOFIN_GROUP_EVENT
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
  devtools:
    livereload:
      enabled: false

topics:
  confirmation-topic: "ECOFIN_CONFIRMATION_PHONE_TOPIC"
  send-code-topic: "ECOFIN_SEND_CODE_TOPIC"

logging:
  level:
    org:
      apache:
        kafka: WARN
    kafka: WARN